### ISSUE TITLE
CDC Defi Wallet

### ISSUE THREAD

**Issue by interruptRQ-c** [acclrate/cronos-dapp-basic-3#2]
Add CDC Defi wallet functionality into the solution expanding customer reach and solution flexibility.  Wallet Connect, Metamask should co-exist and vaults should notice no difference.

**Comment by kentimsit** [comment]
Yes it's already included, see blog post https://medium.com/cronos-chain/cronos-developer-series-build-a-simple-dapp-with-react-crypto-com-defi-wallet-and-metamask-87c37ccd589f
